# IMPORTANT :- SHOULD BE LOCATED IN -> C:/Users/.psmux.conf
#####  PREFIX #####

# Change prefix from Ctrl+b to Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

##### GENERAL #####

# Enable mouse
set -g mouse on

# Start window numbering at 1
set -g base-index 1

# Start pane numbering at 1
set -g pane-base-index 1

# Renumber windows automatically
set -g renumber-windows on

##### SPLITS #####

# Vertical split
bind v split-window -h

# Horizontal split
bind s split-window -v

##### VIM PANE NAVIGATION #####

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

##### PANE RESIZING #####

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

##### WINDOW NAVIGATION #####

bind -r n next-window
bind -r p previous-window

##### SESSION MANAGEMENT #####

# Reload config
bind r source-file ~/.psmux.conf

##### QUALITY OF LIFE #####

# Easier window selection
bind w choose-window

# Zoom pane
bind z resize-pane -Z

# Rename window
bind , command-prompt "rename-window %%"

# Detach session
bind d detach-client
