watch_stylesheet: true
watch_config: true
debug: false
update_check: true

bars:
  primary-bar:
    enabled: true
    screens: ["primary"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      align: "center"
    animation:
      enabled: true
      duration: 500
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: 110
      height: 30
    padding:
      top: 6
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: []
      center: ["cava", "clock"]
      right: ["power_menu"]

widgets:
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      bars_number: 4
      bar_spacing: 2
      bar_width: 2
      sensitivity: 75
      gradient: 1
      gradient_color_1: '#bb9af7'
      gradient_color_2: '#7aa2f7'
      gradient_color_3: '#9ece6a'
      framerate: 60
      sleep_timer: 2
      hide_empty: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 0
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M}"
      label_alt: "{%A, %B %d, %Y}"
      timezones: []
      keybindings:
        - keys: "ctrl+alt+d"
          action: "toggle_calendar"
      calendar:
        alignment: "center"
        offset_left: 0
        offset_top: -30
      callbacks:
        on_left: "toggle_calendar"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      keybindings:
        - keys: "ctrl+alt+p"
          action: "toggle_power_menu"
      uptime: true
      show_user: true
      blur: false
      menu_style: "popup"
      popup:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        offset_top: -30
        offset_left: -55
      profile_image_size: 64
      buttons:
        lock: ["", "Lock"]
        sleep: ["", "Sleep"]
        restart: ["", "Restart"]
        shutdown: ["⏻", "Shut Down"]
        cancel: ["󰜺", "Cancel"]
      callbacks:
        on_left: "toggle_power_menu"
