watch_stylesheet: true
watch_config: true
debug: false
update_check: true

bars:
  primary-bar:
    enabled: true
    screens: ["primary"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      align: "center"
    animation:
      enabled: true
      duration: 500
    blur_effect:
      enabled: true
      dark_mode: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "None"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: 150
      height: 30
    padding:
      top: 6
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: []
      center: ["clock"]
      right: ["power_menu"]

widgets:
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M}"
      label_alt: "{%A, %B %d, %Y}"
      timezones: []
      callbacks:
        on_left: "toggle_calendar"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      keybindings:
        - keys: "ctrl+alt+p"
          action: "toggle_power_menu"
      uptime: true
      show_user: true
      blur: false
      menu_style: "popup"
      popup:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        offset_top: -30
        offset_left: -75
      profile_image_size: 64
      buttons:
        lock: ["\uf023", "Lock"]
        sleep: ["\uf186", "Sleep"]
        restart: ["\uf021", "Restart"]
        shutdown: ["\uf011", "Shut Down"]
        cancel: ["", "Cancel"]
      callbacks:
        on_left: "toggle_power_menu"
